### ISSUE TITLE
Allow referencing external files for templates

### ISSUE THREAD

**Issue by cplee** [stelligent/mu#167]
Add ability to specify an `extensions` section that includes URI of the following forms:

* `<path>` - a relative path to a directory for an extension
* `s3://<bucket>/<prefix>/<filename>.[zip|tar.gz]` - an S3 URL to an extension archive
* `git+<protocol>://[<user>[:<password>]@]<hostname>[:<port>][:][/]<path>[#<commit-ish> | #semver:<semver>]`

The contents will include a list of yml files that will be treated as custom cloudformation to merge with the default cloudformation.  The yml files will match the same filename as the asset being extended (see: https://github.com/stelligent/mu/tree/develop/templates/assets)

Extensions can handle inputs via stack parameters.  The values to pass to the stack parameters can be provided under the `parameters` key.

Sample mu.yml:

```
### Load 2 extensions.  One is in same repo as the mu.yml and another in an S3 bucket
extensions:
- uri: cfn/
- uri: s3://my-mu-extensions/vpn/
  parameters:
    CustomerGWIpAddress: 1.1.1.1
```
