### ISSUE TITLE
Custom Cloudformation breaks the Pipeline template

### ISSUE THREAD

**Issue by akuma12** [stelligent/mu#181]
Mu Version: 0.2.5

If you add custom CloudFormation templates under the templates: key, and tie it to the Pipeline stack (ex. mu-pipeline-servicename), it will cause the stack update or create to fail on the resource AWS::CodePipeline::Pipeline with the error:

`Value of property Stages must be a list of objects`

Example YML:

```
templates:
  mu-pipeline-msp-pipeline-example:
    Outputs:
      PipelineName:
        Value:
          Fn::Sub: ${Pipeline}
        Description: Pipeline Name
        Export:
          Name:
            Fn::Sub: ${AWS::StackName}-Pipeline
```

This error occurs no matter what CloudFormation is added to the stack. Other stacks seem to work just fine.

I've attached 2 separate templates that I generated using --dryrun, and it seems like the two templates are generated completely differently. In the bad-pipeline example, the order of objects is completely different, and it uses Fn::Sub, whereas the good-pipeline example uses !Sub.

[good-pipeline.txt](https://github.com/stelligent/mu/files/1360970/good-pipeline.txt)
[bad-pipeline.txt](https://github.com/stelligent/mu/files/1360971/bad-pipeline.txt)
