### ISSUE TITLE
Parameterised timeouts for pipeline steps

### ISSUE THREAD

**Issue by nilsga** [stelligent/mu#214]
It would be nice if it was possible to override the default timeout of 30 minutes for a pipeline step directly in the pipeline definition in `mu.yml` instead of having to override it with a template definition.

**Comment by cplee** [comment]
Approach:

Add `timeout` to `build`, `acceptance` and `production` nodes of the pipeline in `mu.yml`.  Take those input and pass to the `pipeline.yml` as stack parameters and use in the CodeBuild definitions for `TimeoutInMinutes` (see: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html)

sample mu.yml:

```
service:
  pipeline:
    build:
      timeout: 15
    acceptance:
      timeout: 60
    production:
      timeout: 60
```
