### ISSUE TITLE
Support choosing deployment strategy

### ISSUE THREAD

**Issue by brentley** [stelligent/mu#251]
It looks like the default deployment strategy is "recreate" -- that is, kill the running tasks, then replace them with the new version.  `MinimumHealthyPercent` is set to `0`.  This will cause downtime, but can be useful when having too many of a service can't be tolerated (kafka consumer, for example).

I think the more common approach when dealing with stateless microservices is "blue/green". I've configured my services to deploy with this strategy using this custom cloudformation (example):

```yaml
templates:
  mu-service-example-frontend-myservice:
    Resources:
      EcsService:
        Properties:
          DeploymentConfiguration:
            MaximumPercent: 200
            MinimumHealthyPercent: 100
```

If you wanted to offer a 3rd option, you could consider a "ramped" strategy, that would replace tasks a few at a time until the new version is at 100% deployed.  set `MinimumHealthyPercent` to `50` and `MaximumPercent` to `100`

It would be cool if these choices were rolled up into a single parameter, rather than using custom cloudformation.
