### ISSUE TITLE
Allow multiple ingress rules to be specified for bastion host.

### ISSUE THREAD

**Issue by timbaileyjones** [stelligent/mu#292]
Current `mu` configuration only allows one source CIDR address to be specified for bastion ingress.
```
  cluster: 
    keyName: my-keypair
    sshAllow: 0.0.0.0/0 ```

It would be nice to allow multiple CIDRs to be specified, or (@cplee's suggestion) to allow a specific `sg-xxxxxxxx` to be specified. The latter option would put the customer in charge of their own bastion SG.

**Comment by srp** [comment]
It's  already pretty easy to use the [mu custom cloudformation](https://github.com/stelligent/mu/wiki/Custom-CloudFormation) to add extra security groups:

```
  mu-vpc-acceptance:
    Resources:
      BastionHost:
        Properties:
          NetworkInterfaces:
            Fn::Splice:
              - 0
              - 1
              - - GroupSet:
                    - "sg-123456..."
```
