### ISSUE TITLE
Support additional containers per task definition

### ISSUE THREAD

**Issue by cplee** [stelligent/mu#297]
Need to be able to specify sidecar containers for things like monitoring agents that run in the same task, but as a separate container.

**Comment by zsims** [comment]
I'm looking at picking this up, do you have anything in mind for what the interface/`mu.yml` would look like for this case? E.g. being able to specify docker images for additional containers?

**Comment by cplee** [comment]
@zsims thinking something like this:

```
service:
  sidecars:
    imageRepository: my/image
    cpu: 20
    memory: 400
    environment:
      FOO: bar
```
