### ISSUE TITLE
Quickstart Basic Guide Fails on mu pipeline up

### ISSUE THREAD

**Issue by mneil** [stelligent/mu#318]
I'm receiving this error in cloudwatch

```
arn:aws:sts::324320755747:assumed-role/mu-pipeline-mu-ci-us-west-2/AWSCodeBuild-9264ba60-3463-48f6-9891-bad3e7cfab95 is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:us-west-2:324320755747:stack/mu-repo-mu-quickstart/*
```

I checked the role mu-pipeline-mu-ci-us-west-2 and it has these permissions:

```
[
        {
            "Action": [
                "cloudformation:CreateStack",
                "cloudformation:UpdateStack",
                "cloudformation:DescribeStackEvents"
            ],
            "Resource": [
                "arn:aws:cloudformation:us-west-2:324320755747:stack/mu-repo-mu/*",
                "arn:aws:cloudformation:us-west-2:324320755747:stack/mu-app-mu/*",
                "arn:aws:cloudformation:us-west-2:324320755747:stack/mu-bucket-codedeploy/*"
            ],
            "Effect": "Allow"
        },
```

It seems that the resource it granted access to does not match the stack it attempted to access. As I type this I wonder if it's related to the - in the repository name `mu-quickstart`?

mu 1.5.1
osx
my.yml
```
environments:
  - name: acceptance
  - name: production
service:
  port: 80
  healthEndpoint: /
  pathPatterns:
    - /*
  pipeline:
    source:
      provider: GitHub
      repo: mneil/mu-quickstart
```
