### ISSUE TITLE
memory and cpu separate for acceptancee and production environment?

### ISSUE THREAD

**Issue by tushar-borole** [stelligent/mu#349]
can I specify memory and CPU separate for acceptance and production environment
right now I have the same for both acceptance and production.

```yml
service:
  name: frontend
  desiredCount: 4
  minSize: 2
  maxSize: 8
  port: 8081
  memory: 1024
  cpu: 512
```
