### ISSUE TITLE
Unable to dry run when provider is eks

### ISSUE THREAD

**Issue by mneil** [stelligent/mu#393]
`mu.yml`

```
---
environments:
  - name: acceptance
    provider: eks
  - name: production
    provider: eks
service:
    acceptance:
      disabled: true
    production:
      disabled: true
```

Run `mu -d env up acceptance`

What I expect to happen: CFN templates generated in a temporary folder.

What actually happens: I receive an error during the "Upserting environment 'acceptance'" stage>
```
ResourceNotFoundException: No cluster found for name: mu-eks-workshop-environment-acceptance.
        status code: 404, request id: afeea07c-e2cb-11e8-9d24-7f94881ec1a7
```
