### ISSUE TITLE
How to use AWS Parameter Store in mu.yml

### ISSUE THREAD

**Issue by danielpetroianu** [stelligent/mu#397]
I'm trying to use AWS Parameter Store as described in this video / sample
https://youtu.be/mfRkQpZjEHo?t=665
https://github.com/stelligent/mu/blob/develop/examples/database/mu.yml

My mu.yml is in the form of:
```
environments:
  - name: acceptance
    provider: ecs
service:
      name: sample-app
      #...
      environment:
        DATABASE_URI: 
          acceptance: mongodb://${acceptance_DATABASE_USERNAME}:${acceptance_DATABASE_PASSWORD}@domain...
          production: mongodb://${production_DATABASE_USERNAME}:${production_DATABASE_PASSWORD}@domain...
````
    
But in my Code Build mu-pipeline-sample-app-deploy-acceptance I get this error

    ERROR ·ValidationError: Template format error: Unresolved resource dependencies [acceptance_DATABASE_PASSWORD, acceptance_DATABASE_USERNAME] in the Resources block of the template
    status code: 400, request id:...

What is the problem, do I need to configure something before hand?
