### ISSUE TITLE
Bitbucket support?

### ISSUE THREAD

**Issue by JoHuang** [stelligent/mu#417]
Hi

Thanks for this great tool.
Is it possible to deploy code from Bitbucket?

Thanks

**Comment by mneil** [comment]
Mu uses [CodePipeline](https://aws.amazon.com/codepipeline/) which only accepts a source of GitHub, S3, or CodeCommit.

If you did not want to use CodePipeline at all you could (mostly) reproduce what codepipeline does with [bitbucket pipelines](https://bitbucket.org/product/features/pipelines) on your own. Another way to possibly handle it is to add [custom cloudformation](https://github.com/stelligent/mu/wiki/Custom-CloudFormation) to your mu configuration to setup integration with [commit hooks and lambda](https://aws.amazon.com/blogs/devops/using-custom-source-actions-in-aws-codepipeline-for-increased-visibility-for-third-party-source-control/).

**Comment by chris-d-edwards** [comment]
there is a BitBucket CodeDeploy plugin. Worth an experiment ?

**Comment by richard-smith-sky** [comment]
I've been able to get _mu_ working with a BitBucket source using S3 as an intermediate step without too much trouble. In our case we are using a **CICD** approach so I make BitBucket Pipelines zip my code and push it to S3 using an awscli command before then running the _mu_ command with config that references the S3 source rather than the git repo.

**bitbucket-pipelines.yml**
```
image: earthi/mu:latest

pipelines:
  branches:
    master:
      - step:
          name: Build service artifacts and deploy to S3
          script:
            - zip -r s3-service.zip .
            - aws s3 cp s3-service.zip s3://my-s3-bucket/
      - step:
          name: Start mu pipeline deployment of artifacts to AWS
          deployment: production
          script:
            - mu -r eu-west-1 pipeline up    // or some other mu command
```

**mu.yml**
```
...
  pipeline:
    source:
      provider: S3
      repo: my-s3-bucket/s3-service.zip
```
