### ISSUE TITLE
Panic during deploy if integer environment variable present

### ISSUE THREAD

**Issue by mattbucci** [stelligent/mu#422]
I had the following in my yml file,  I assume I can get around this by just quoting the number, which I have done. I'm writing this as I wait for it to redeploy

``` 
environment:
    APP_ENV:
      acceptance: qa
      production: production
    REDIS_HOST:
      acceptance: omitted
      production: omitted
    REDIS_PORT:
      acceptance: 6379
      production: 6379
```

This resulted in "panic: interface conversion: interface {} is int, not string" while deploying to acceptance environment
