### ISSUE TITLE
Using mu service exec results in aws error

### ISSUE THREAD

**Issue by masha256** [stelligent/mu#432]
service deploys, restart, seeing logs all work, so I think my mu config is fine.

mu.yml:

```
environments:
  - name: production
    provider: ecs-fargate
    loadbalancer:
      certificate: "aaaaaa"
    vpcTarget:
      vpcId: vpc-xxx
      instanceSubnetIds:
        - subnet-123
        - subnet-987
      elbSubnetIds:
        - subnet-abc
        - subnet-def

service:
  name: vinaio-app                   # The unique name of the service (default: the name of the directory that mu.yml was in)
  desiredCount: 1                    # The desired number of tasks to run for the service (default: 2)
  port: 80                           # The port to expose from the container (default: 8080)
  protocol: HTTP                     # The protocol for the port exposed from the container (default: HTTP)
  healthEndpoint: /                  # The endpoint inside the container to determine if the task is healthy (default: /health)
  cpu: 256                           # The number of CPU units to allocate to each task (default: 10)
  memory: 512                        # The amount of memory in MiB to allocate to each task (default: 300)
  networkMode: awsvpc                # The networking mode for the task: none, bridge, host, or awsvpc (default: bridge)
  minSize: 1                         # The minimum number of services for autoscaling (default: 1)
  maxSize: 2                         # The maximum number of services for autoscaling (default: 2)
  deploymentStrategy: blue_green     # The strategy for deploying new images: blue_green, rolling, replace (default: blue_green)

  pathPatterns:
    - /*

  environment:
    RUN_TARGET: web
    RAILS_ENV:
      acceptance: acceptance
      production: production
    SECRETS_BUCKET:
      production: vinaio-secrets-production
```

Then trying to run:
```
mu -V service exec production rake db:migrate
```

and get
```
(truncated...)
Executing command '[[rake db:migrate]]' on environment 'production' for service 'vinaio-app'

Getting stack 'mu-service-vinaio-app-production'...
09:49:15.465 aws ▶ 02c Searching for stack named 'mu-service-vinaio-app-production'
09:49:25.848 aws ▶ 02d Environment: production, Service: vinaio-app, Cluster: mu-environment-production, Task: arn:aws:ecs:us-west-1:xxxx:task-definition/mu-service-vinaio-app-production:22
09:49:25.848 aws ▶ 02e ECS Input Contents: {
  Cluster: "mu-environment-production",
  Count: 1,
  Overrides: {
    ContainerOverrides: [{
        Command: ["rake","db:migrate"],
        Name: "vinaio-app"
      }]
  },
  TaskDefinition: "arn:aws:ecs:us-west-1:xxxx:task-definition/mu-service-vinaio-app-production:22"
}
09:49:36.228 aws ▶ 02f ECS Result Contents: {

}, InvalidParameterException: Network Configuration must be provided when networkMode 'awsvpc' is specified.
	status code: 400, request id: 1120ae6e-887b-11e9-a372-3b14a630b694
Command execution complete

The following error has occurred executing the command:  'InvalidParameterException: Network Configuration must be provided when networkMode 'awsvpc' is specified.
	status code: 400, request id: 1120ae6e-887b-11e9-a372-3b14a630b694'
func1 ▶ ERROR  InvalidParameterException: Network Configuration must be provided when networkMode 'awsvpc' is specified.
	status code: 400, request id: 1120ae6e-887b-11e9-a372-3b14a630b694
09:49:36.228 workflows ▶ 033 InvalidParameterException: Network Configuration must be provided when networkMode 'awsvpc' is specified.
	status code: 400, request id: 1120ae6e-887b-11e9-a372-3b14a630b694
```
