### ISSUE TITLE
Please support ELB CertificateArn

### ISSUE THREAD

**Issue by mfrawley** [stelligent/mu#445]
Hi there,
 I have an issue that I cannot correctly configure the Certificate for my ELB because there's an implicit assumption that the Certificate and the stack will be in the same region. Would it be possible to add support for specifying the full certificate ARN? I was 95% finished setting up my app when I hit this and it's an absolutely blocker for me to continue using mu. Many thanks.

My setup:
mu version 1.5.10
on macOS Catalina 10.15.3

Excerpt from my mu.yml:

```
environments:
  - name: dev
    loadbalancer:
      hostedzone: foo.bar
      name: analytics
      certificate: "arn:aws:acm:us-east-1:xxx:certificate/foo-bar"
```
Reminder: My mu stack is in eu-central-1 not us-east-1, and I cannot change this.
