### ISSUE TITLE
Custom tags on stacks

### ISSUE THREAD

**Issue by cplee** [stelligent/mu#88]
Allow specifying custom tags in mu.yml for environments, pipelines and services

Example:

```
environments:
  - name: dev
    tags:
       CostCenter: sales
       OwnerContact: me@stelligent.com
 ```
